// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	analysis "github.com/jsjj2598-bit/video-dna/service/videodna/api/internal/handler/analysis"
	components "github.com/jsjj2598-bit/video-dna/service/videodna/api/internal/handler/components"
	export "github.com/jsjj2598-bit/video-dna/service/videodna/api/internal/handler/export"
	media "github.com/jsjj2598-bit/video-dna/service/videodna/api/internal/handler/media"
	studio "github.com/jsjj2598-bit/video-dna/service/videodna/api/internal/handler/studio"
	system "github.com/jsjj2598-bit/video-dna/service/videodna/api/internal/handler/system"
	"github.com/jsjj2598-bit/video-dna/service/videodna/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 异步上传并分析视频
				Method:  http.MethodPost,
				Path:    "/analyze",
				Handler: analysis.AnalyzeHandler(serverCtx),
			},
			{
				// 同步上传并等待视频分析完成
				Method:  http.MethodPost,
				Path:    "/analyze/wait",
				Handler: analysis.AnalyzeWaitHandler(serverCtx),
			},
			{
				// 查询分析任务进度
				Method:  http.MethodGet,
				Path:    "/progress/:session_id",
				Handler: analysis.ProgressHandler(serverCtx),
			},
			{
				// 读取完整 Video DNA 分析结果
				Method:  http.MethodGet,
				Path:    "/result/:session_id",
				Handler: analysis.ResultHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithTimeout(1800000*time.Millisecond),
		rest.WithMaxBytes(2147483648),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取模型、组件、技能和插件
				Method:  http.MethodGet,
				Path:    "/components",
				Handler: components.ComponentsHandler(serverCtx),
			},
			{
				// 启用或关闭分析组件
				Method:  http.MethodPost,
				Path:    "/components/:component_id/toggle",
				Handler: components.ComponentToggleHandler(serverCtx),
			},
			{
				// 创建自定义 AI 模型
				Method:  http.MethodPost,
				Path:    "/models",
				Handler: components.ModelCreateHandler(serverCtx),
			},
			{
				// 更新自定义 AI 模型
				Method:  http.MethodPut,
				Path:    "/models/:model_id",
				Handler: components.ModelUpdateHandler(serverCtx),
			},
			{
				// 删除自定义 AI 模型
				Method:  http.MethodDelete,
				Path:    "/models/:model_id",
				Handler: components.ModelDeleteHandler(serverCtx),
			},
			{
				// 测试 AI 模型连通性
				Method:  http.MethodPost,
				Path:    "/models/:model_id/test",
				Handler: components.ModelTestHandler(serverCtx),
			},
			{
				// 获取插件列表
				Method:  http.MethodGet,
				Path:    "/plugins",
				Handler: components.PluginsHandler(serverCtx),
			},
			{
				// 删除用户安装的插件
				Method:  http.MethodDelete,
				Path:    "/plugins/:plugin_id",
				Handler: components.PluginDeleteHandler(serverCtx),
			},
			{
				// 安装受信任的可执行插件 ZIP
				Method:  http.MethodPost,
				Path:    "/plugins/install",
				Handler: components.PluginInstallHandler(serverCtx),
			},
			{
				// 创建自定义技能
				Method:  http.MethodPost,
				Path:    "/skills",
				Handler: components.SkillCreateHandler(serverCtx),
			},
			{
				// 删除自定义技能
				Method:  http.MethodDelete,
				Path:    "/skills/:skill_id",
				Handler: components.SkillDeleteHandler(serverCtx),
			},
			{
				// 对指定分析结果运行技能
				Method:  http.MethodPost,
				Path:    "/skills/:skill_id/run",
				Handler: components.SkillRunHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithMaxBytes(52428800),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 导出剪映草稿目录
				Method:  http.MethodPost,
				Path:    "/draft/export",
				Handler: export.DraftExportHandler(serverCtx),
			},
			{
				// 导出 EDL、FCP7 XML、Cutmark、SRT 或 ZIP
				Method:  http.MethodPost,
				Path:    "/export",
				Handler: export.ExportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取分析历史列表
				Method:  http.MethodGet,
				Path:    "/history",
				Handler: media.HistoryListHandler(serverCtx),
			},
			{
				// 清空已完成的分析历史
				Method:  http.MethodDelete,
				Path:    "/history",
				Handler: media.HistoryClearHandler(serverCtx),
			},
			{
				// 获取单条历史分析详情
				Method:  http.MethodGet,
				Path:    "/history/:session_id",
				Handler: media.HistoryDetailHandler(serverCtx),
			},
			{
				// 删除指定分析历史
				Method:  http.MethodDelete,
				Path:    "/history/:session_id",
				Handler: media.HistoryDeleteHandler(serverCtx),
			},
			{
				// 读取镜头关键帧
				Method:  http.MethodGet,
				Path:    "/sessions/:session_id/frames/:filename",
				Handler: media.SessionFrameHandler(serverCtx),
			},
			{
				// 读取支持 Range 的源视频
				Method:  http.MethodGet,
				Path:    "/sessions/:session_id/video",
				Handler: media.SessionVideoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 将内置节奏模板应用到新视频
				Method:  http.MethodPost,
				Path:    "/ai/apply",
				Handler: studio.AiApplyHandler(serverCtx),
			},
			{
				// 根据分析结果推荐 BGM
				Method:  http.MethodPost,
				Path:    "/ai/bgm",
				Handler: studio.AiBgmHandler(serverCtx),
			},
			{
				// 生成短视频分镜
				Method:  http.MethodPost,
				Path:    "/ai/storyboard",
				Handler: studio.AiStoryboardHandler(serverCtx),
			},
			{
				// 获取内置节奏模板
				Method:  http.MethodGet,
				Path:    "/ai/templates",
				Handler: studio.AiTemplatesHandler(serverCtx),
			},
			{
				// 将示例视频节奏模板应用到新视频
				Method:  http.MethodPost,
				Path:    "/template/apply",
				Handler: studio.TemplateApplyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithTimeout(1800000*time.Millisecond),
		rest.WithMaxBytes(2147483648),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 服务健康检查
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: system.HealthHandler(serverCtx),
			},
		},
	)
}
