// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AnalyzeAcceptedResp struct {
	SessionId string `json:"session_id"` // 分析会话 ID
	Status    string `json:"status"`     // 状态：running=运行中
}

type AnalyzeReq struct {
	Detector  string `form:"detector,optional"`   // 镜头检测器：content 或 adaptive
	Backend   string `form:"backend,optional"`    // 描述后端：auto/openai/qwen/heuristic
	SessionId string `form:"session_id,optional"` // 可选自定义会话 ID
}

type ComponentToggleReq struct {
	ComponentId string `path:"component_id"`      // 组件 ID
	Enabled     bool   `json:"enabled"`           // 是否启用
	ModelId     string `json:"model_id,optional"` // 绑定模型 ID
}

type CutItem struct {
	Index         int64   `json:"index,optional"`           // 区间序号，从 0 开始
	Start         float64 `json:"start"`                    // 开始时间，单位秒
	End           float64 `json:"end"`                      // 结束时间，单位秒
	Duration      float64 `json:"duration,optional"`        // 区间时长，单位秒
	AlignedToBeat bool    `json:"aligned_to_beat,optional"` // 是否吸附到节拍
}

type DnaSessionReq struct {
	SessionId string `json:"session_id,optional"` // 分析会话 ID
}

type DraftExportReq struct {
	SessionId   string    `json:"session_id"`            // 分析会话 ID
	ProjectName string    `json:"project_name,optional"` // 工程名称
	DownloadDir string    `json:"download_dir,optional"` // 自定义输出目录
	Cuts        []CutItem `json:"cuts"`                  // 剪辑区间
}

type EmptyResp struct {
}

type ExportReq struct {
	Format string `form:"fmt,optional"` // 格式：edl/fcp7xml/cutmark/srt/all
}

type HistoryItem struct {
	SessionId  string  `json:"session_id"`   // 分析会话 ID
	Name       string  `json:"name"`         // 源视频文件名
	Time       string  `json:"time"`         // 分析完成时间
	TotalShots int64   `json:"total_shots"`  // 镜头数量
	Duration   float64 `json:"duration"`     // 视频时长，单位秒
	Bpm        float64 `json:"bpm,optional"` // 估算 BPM
	Summary    string  `json:"summary"`      // 分析摘要
	HasVideo   bool    `json:"has_video"`    // 是否保留源视频
	ShotCount  int64   `json:"shot_count"`   // 镜头数量
}

type HistoryListResp struct {
	Items []HistoryItem `json:"items"` // 按更新时间倒序排列的历史记录
}

type ModelPathReq struct {
	ModelId string `path:"model_id"` // 模型 ID
}

type ModelReq struct {
	ModelId  string `path:"model_id,optional" json:"id,optional"` // 模型 ID
	Name     string `json:"name"`                                 // 展示名称
	Kind     string `json:"kind"`                                 // 类型：vision 或 chat
	Provider string `json:"provider"`                             // 提供方：openai/dashscope/ollama/custom
	BaseUrl  string `json:"base_url"`                             // OpenAI 兼容接口根地址
	Model    string `json:"model"`                                // 模型名称
	ApiKey   string `json:"api_key,optional"`                     // API Key；更新时留空表示保留旧值
}

type OkResp struct {
	Ok bool `json:"ok"` // 操作是否成功
}

type PluginPathReq struct {
	PluginId string `path:"plugin_id"` // 插件 ID
}

type ProgressLog struct {
	Time    string `json:"t"`     // 日志时间，格式 HH:mm:ss
	Stage   string `json:"stage"` // 分析阶段
	Percent int64  `json:"pct"`   // 阶段总进度，范围 0-100
	Message string `json:"msg"`   // 用户可读日志
}

type ProgressResp struct {
	SessionId string        `json:"session_id"`     // 分析会话 ID
	Stage     string        `json:"stage"`          // 当前阶段
	Percent   int64         `json:"pct"`            // 总进度，范围 0-100
	Logs      []ProgressLog `json:"logs"`           // 最近进度日志
	Error     string        `json:"error,optional"` // 失败原因
	Done      bool          `json:"done"`           // 是否已结束
}

type RhythmTemplate struct {
	Id      string    `json:"id"`      // 模板 ID
	Name    string    `json:"name"`    // 模板名称
	Desc    string    `json:"desc"`    // 模板说明
	Icon    string    `json:"icon"`    // 展示图标
	Bpm     float64   `json:"bpm"`     // 建议 BPM
	Shot    float64   `json:"shot"`    // 建议平均镜头时长
	Pattern []float64 `json:"pattern"` // 镜头时长模式
}

type SessionFrameReq struct {
	SessionId string `path:"session_id"` // 分析会话 ID
	Filename  string `path:"filename"`   // 关键帧文件名
}

type SessionReq struct {
	SessionId string `path:"session_id"` // 分析会话 ID
}

type SkillPathReq struct {
	SkillId string `path:"skill_id"` // 技能 ID
}

type SkillReq struct {
	Id     string `json:"id,optional"`   // 技能 ID
	Name   string `json:"name"`          // 技能名称
	Desc   string `json:"desc,optional"` // 技能说明
	Prompt string `json:"prompt"`        // 提示词模板
}

type SkillRunReq struct {
	SkillId   string `path:"skill_id"`            // 技能 ID
	SessionId string `json:"session_id,optional"` // 分析会话 ID
}

type StoryboardReq struct {
	Topic  string `json:"topic"`           // 主题或文案
	Length int64  `json:"length,optional"` // 镜头数量，范围 3-20
}

type TemplateListResp struct {
	Templates []RhythmTemplate `json:"templates"` // 可选模板列表
}
